development: &defaults
  adapter:  sqlite
  database: db/memorizr_dev.sqlite3
  username: root
  password:
  host: localhost

test:
  <<:       *defaults
  database: db/memorizr_test.sqlite3

production:
  <<:       *defaults
  database: db/memorizr_production.sqlite3

rake:
  <<: *defaults
