development: &defaults
  adapter:  postgres
  database: memorizr_dev
  username: postgres
  password:
  host: localhost

test:
  <<:       *defaults
  database: memorizr_test

production:
  <<:       *defaults
  database: memorizr_production

rake:
  <<: *defaults
